name: hrm
channels:
        - cbetters
dependencies:
        - numpy
        - csvkit
        - ipython
        - pytest
        - pytest-cov
        - pytest-pep8
        - scipy
        - peakutils
